server:
  port: 8888

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.example.demo: debug
  config: classpath:log4j2-config.xml

spring:
  application:
    name: mydemo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: 192.168.1.20 # Redis 服务器地址
    port: 6379 # Redis 服务器连接端口
    password:  # Redis 服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0

# 不配置会出现空指针问题
caching:
  ttlmap:
    teacher: 60
    teacherAll: 60