server:
  port: 8888


#mapper文件位置,mybatis配置文件位置 ,驼峰与数据库字段的自动映射
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#设置某包下日志级别降低打印
logging:
  level:
    com.example.demo: debug


spring:
  application:
    name: mydemo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver


